"""initial migration

Revision ID: b61ba06825f4
Revises: 4cfa965b47b9
Create Date: 2021-06-17 22:07:22.482435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b61ba06825f4'
down_revision = '4cfa965b47b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_list', sa.String(length=255), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('populars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('populars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('overview', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='populars_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='populars_pkey')
    )
    op.drop_table('movies')
    # ### end Alembic commands ###
